import type { Monaco } from "@monaco-editor/react";

export function defineFtcMonacoThemes(monaco: Monaco) {
  monaco.editor.defineTheme("ftc-dark", {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "52525b", fontStyle: "italic" },
      { token: "keyword", foreground: "818cf8" },
      { token: "keyword.control", foreground: "c084fc" },
      { token: "string", foreground: "4ade80" },
      { token: "string.escape", foreground: "86efac" },
      { token: "number", foreground: "fb923c" },
      { token: "type", foreground: "38bdf8" },
      { token: "type.identifier", foreground: "7dd3fc" },
      { token: "annotation", foreground: "fbbf24" },
      { token: "delimiter", foreground: "52525b" },
    ],
    colors: {
      "editor.background": "#18181f",
      "editor.foreground": "#e4e4e7",
      "editor.lineHighlightBackground": "#18181b80",
      "editor.selectionBackground": "#1e3a5f",
      "editor.inactiveSelectionBackground": "#27272a",
      "editorLineNumber.foreground": "#3f3f46",
      "editorLineNumber.activeForeground": "#71717a",
      "editorCursor.foreground": "#f59e0b",
      "editorCursor.background": "#18181f",
      "editorIndentGuide.background1": "#27272a",
      "editorIndentGuide.activeBackground1": "#3f3f46",
      "editorGutter.background": "#18181f",
      "editorWidget.background": "#18181b",
      "editorWidget.border": "#27272a",
      "editorSuggestWidget.background": "#18181b",
      "editorSuggestWidget.border": "#27272a",
      "editorSuggestWidget.selectedBackground": "#27272a",
      "scrollbar.shadow": "#00000000",
      "scrollbarSlider.background": "#27272a80",
      "scrollbarSlider.hoverBackground": "#3f3f46",
      "scrollbarSlider.activeBackground": "#52525b",
      "editor.wordHighlightBackground": "#27272a",
    },
  });

  monaco.editor.defineTheme("ftc-light", {
    base: "vs",
    inherit: true,
    rules: [
      { token: "comment", foreground: "6b7280", fontStyle: "italic" },
      { token: "keyword", foreground: "4338ca" },
      { token: "keyword.control", foreground: "7c3aed" },
      { token: "string", foreground: "16a34a" },
      { token: "string.escape", foreground: "15803d" },
      { token: "number", foreground: "ea580c" },
      { token: "type", foreground: "0284c7" },
      { token: "type.identifier", foreground: "0369a1" },
      { token: "annotation", foreground: "d97706" },
      { token: "delimiter", foreground: "9ca3af" },
    ],
    colors: {
      "editor.background": "#ffffff",
      "editor.foreground": "#1c1c1e",
      "editor.lineHighlightBackground": "#f3f4f680",
      "editor.selectionBackground": "#add6ff",
      "editor.inactiveSelectionBackground": "#e5e7eb",
      "editorLineNumber.foreground": "#9ca3af",
      "editorLineNumber.activeForeground": "#6b7280",
      "editorCursor.foreground": "#f59e0b",
      "editorIndentGuide.background1": "#e5e7eb",
      "editorIndentGuide.activeBackground1": "#9ca3af",
      "editorGutter.background": "#ffffff",
      "editorWidget.background": "#f9fafb",
      "editorWidget.border": "#e5e7eb",
      "editorSuggestWidget.background": "#ffffff",
      "editorSuggestWidget.border": "#e5e7eb",
      "editorSuggestWidget.selectedBackground": "#f3f4f6",
      "scrollbar.shadow": "#00000000",
      "scrollbarSlider.background": "#d1d5db80",
      "scrollbarSlider.hoverBackground": "#9ca3af",
      "scrollbarSlider.activeBackground": "#6b7280",
      "editor.wordHighlightBackground": "#fef9c3",
    },
  });
}
