import * as Blockly from "blockly/core";

let registered = false;

export function registerFtcBlocks(): void {
  if (registered) return;
  registered = true;

  const S = {
    structure: "structure_blocks",
    motor: "motor_blocks",
    servo: "servo_blocks",
    gamepad: "gamepad_blocks",
    timing: "timing_blocks",
    telemetry: "telemetry_blocks",
    control: "control_blocks",
    advanced: "advanced_blocks",
    math: "math_blocks",
  };

  Blockly.common.defineBlocksWithJsonArray([
    {
      type: "ftc_program",
      message0: "FTC OpMode %1",
      args0: [{ type: "field_label", name: "LABEL", text: "Program" }],
      message1: "Class fields %1",
      args1: [{ type: "input_statement", name: "FIELD_STACK", check: "ftc_field" }],
      message2: "Helper methods %1",
      args2: [{ type: "input_statement", name: "METHOD_STACK", check: "ftc_method" }],
      message3: "Init (before Start) %1",
      args3: [{ type: "input_statement", name: "INIT_STACK", check: "ftc_statement" }],
      message4: "Match loop %1",
      args4: [{ type: "input_statement", name: "LOOP_STACK", check: "ftc_statement" }],
      style: S.structure,
      tooltip: "Top-level OpMode structure. Do not delete.",
      helpUrl: "",
      deletable: false,
      movable: false,
    },
    {
      type: "ftc_declare_dc_motor",
      message0: "declare DcMotor %1",
      args0: [{ type: "field_input", name: "NAME", text: "leftMotor" }],
      previousStatement: "ftc_field",
      nextStatement: "ftc_field",
      style: S.structure,
    },
    {
      type: "ftc_declare_dc_motor_ex",
      message0: "declare DcMotorEx %1",
      args0: [{ type: "field_input", name: "NAME", text: "shooterMotor" }],
      previousStatement: "ftc_field",
      nextStatement: "ftc_field",
      style: S.structure,
    },
    {
      type: "ftc_declare_servo",
      message0: "declare Servo %1",
      args0: [{ type: "field_input", name: "NAME", text: "armServo" }],
      previousStatement: "ftc_field",
      nextStatement: "ftc_field",
      style: S.structure,
    },
    {
      type: "ftc_declare_cr_servo",
      message0: "declare CRServo %1",
      args0: [{ type: "field_input", name: "NAME", text: "intakeServo" }],
      previousStatement: "ftc_field",
      nextStatement: "ftc_field",
      style: S.structure,
    },
    {
      type: "ftc_declare_elapsed_time",
      message0: "declare ElapsedTime %1",
      args0: [{ type: "field_input", name: "NAME", text: "timer" }],
      previousStatement: "ftc_field",
      nextStatement: "ftc_field",
      style: S.structure,
    },
    {
      type: "ftc_declare_boolean",
      message0: "declare boolean %1 = %2",
      args0: [
        { type: "field_input", name: "NAME", text: "lastA" },
        { type: "field_checkbox", name: "VALUE", checked: false },
      ],
      previousStatement: "ftc_field",
      nextStatement: "ftc_field",
      style: S.structure,
    },
    {
      type: "ftc_declare_int",
      message0: "declare int %1 = %2",
      args0: [
        { type: "field_input", name: "NAME", text: "loopCount" },
        { type: "field_number", name: "VALUE", value: 0 },
      ],
      previousStatement: "ftc_field",
      nextStatement: "ftc_field",
      style: S.structure,
    },
    {
      type: "ftc_declare_double",
      message0: "declare double %1 = %2",
      args0: [
        { type: "field_input", name: "NAME", text: "boostMultiplier" },
        { type: "field_number", name: "VALUE", value: 1, min: -1, max: 1, precision: 0.1 },
      ],
      previousStatement: "ftc_field",
      nextStatement: "ftc_field",
      style: S.structure,
    },
    {
      type: "ftc_private_double_method",
      message0: "private double %1 ( ) { return %2 ; }",
      args0: [
        { type: "field_input", name: "NAME", text: "getForwardPower" },
        { type: "field_input", name: "BODY", text: "-gamepad1.left_stick_y" },
      ],
      previousStatement: "ftc_method",
      nextStatement: "ftc_method",
      style: S.structure,
    },
    {
      type: "ftc_hw_get_dc_motor",
      message0: "%1 = hardwareMap.get(DcMotor, %2)",
      args0: [
        { type: "field_input", name: "VAR", text: "leftMotor" },
        { type: "field_input", name: "HW", text: "left_motor" },
      ],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.motor,
    },
    {
      type: "ftc_hw_get_dc_motor_ex",
      message0: "%1 = hardwareMap.get(DcMotorEx, %2)",
      args0: [
        { type: "field_input", name: "VAR", text: "shooterMotor" },
        { type: "field_input", name: "HW", text: "shooter_motor" },
      ],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.motor,
    },
    {
      type: "ftc_hw_get_servo",
      message0: "%1 = hardwareMap.get(Servo, %2)",
      args0: [
        { type: "field_input", name: "VAR", text: "blockerServo" },
        { type: "field_input", name: "HW", text: "blocker_servo" },
      ],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.servo,
    },
    {
      type: "ftc_hw_get_cr_servo",
      message0: "%1 = hardwareMap.get(CRServo, %2)",
      args0: [
        { type: "field_input", name: "VAR", text: "intakeServo" },
        { type: "field_input", name: "HW", text: "intake_servo" },
      ],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.servo,
    },
    {
      type: "ftc_set_direction",
      message0: "%1.setDirection( %2 )",
      args0: [
        { type: "field_input", name: "MOTOR", text: "leftMotor" },
        {
          type: "field_dropdown",
          name: "DIR",
          options: [
            ["FORWARD", "FORWARD"],
            ["REVERSE", "REVERSE"],
          ],
        },
      ],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.motor,
    },
    {
      type: "ftc_set_zero_power_behavior",
      message0: "%1.setZeroPowerBehavior( %2 )",
      args0: [
        { type: "field_input", name: "MOTOR", text: "leftMotor" },
        {
          type: "field_dropdown",
          name: "MODE",
          options: [
            ["BRAKE", "BRAKE"],
            ["FLOAT", "FLOAT"],
          ],
        },
      ],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.motor,
    },
    {
      type: "ftc_motor_set_power",
      message0: "%1.setPower( %2 )",
      args0: [
        { type: "field_input", name: "MOTOR", text: "leftMotor" },
        { type: "input_value", name: "POWER", check: "Number" },
      ],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.motor,
    },
    {
      type: "ftc_motor_set_power_negated_stick",
      message0: "%1.setPower( -gamepad1.left_stick_y )",
      args0: [{ type: "field_input", name: "MOTOR", text: "leftMotor" }],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.gamepad,
    },
    {
      type: "ftc_motor_set_power_helper",
      message0: "%1.setPower( %2() )",
      args0: [
        { type: "field_input", name: "MOTOR", text: "driveMotor" },
        { type: "field_input", name: "HELPER", text: "getForwardPower" },
      ],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.gamepad,
    },
    {
      type: "ftc_motor_set_power_stick_boost",
      message0: "%1.setPower( -gamepad1.left_stick_y * %2 )",
      args0: [
        { type: "field_input", name: "MOTOR", text: "driveMotor" },
        { type: "field_input", name: "BOOST", text: "boostMultiplier" },
      ],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.gamepad,
    },
    {
      type: "ftc_cr_servo_set_power",
      message0: "%1.setPower( %2 )",
      args0: [
        { type: "field_input", name: "SERVO", text: "intakeServo" },
        { type: "input_value", name: "POWER", check: "Number" },
      ],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.servo,
    },
    {
      type: "ftc_cr_servo_set_power_trigger",
      message0: "if gamepad1.right_trigger > 0.05 then %1.setPower( gamepad1.right_trigger )",
      args0: [{ type: "field_input", name: "SERVO", text: "intakeServo" }],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.gamepad,
    },
    {
      type: "ftc_servo_set_position",
      message0: "%1.setPosition( %2 )",
      args0: [
        { type: "field_input", name: "SERVO", text: "blockerServo" },
        { type: "field_number", name: "POS", value: 0.5, min: 0, max: 1, precision: 0.05 },
      ],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.servo,
    },
    {
      type: "ftc_servo_set_position_button",
      message0: "if gamepad1.%1 then %2.setPosition( %3 )",
      args0: [
        {
          type: "field_dropdown",
          name: "BTN",
          options: [
            ["a", "a"],
            ["b", "b"],
            ["x", "x"],
            ["y", "y"],
          ],
        },
        { type: "field_input", name: "SERVO", text: "blockerServo" },
        { type: "field_number", name: "POS", value: 1, min: 0, max: 1, precision: 0.05 },
      ],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.gamepad,
    },
    {
      type: "ftc_sleep_after_servo",
      message0: "sleep( %1 ) after servo move",
      args0: [{ type: "field_number", name: "MS", value: 500, min: 0 }],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.timing,
    },
    {
      type: "ftc_encoder_move",
      message0: "encoder move %1 to %2 ticks power %3",
      args0: [
        { type: "field_input", name: "MOTOR", text: "driveMotor" },
        { type: "field_number", name: "TICKS", value: 500 },
        { type: "field_number", name: "POWER", value: 0.6, min: 0.1, max: 1, precision: 0.1 },
      ],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.motor,
    },
    {
      type: "ftc_run_using_encoder",
      message0: "%1.setMode( RUN_USING_ENCODER )",
      args0: [{ type: "field_input", name: "MOTOR", text: "shooterMotor" }],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.motor,
    },
    {
      type: "ftc_set_velocity",
      message0: "%1.setVelocity( %2 )",
      args0: [
        { type: "field_input", name: "MOTOR", text: "shooterMotor" },
        { type: "field_number", name: "TPS", value: 1500 },
      ],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.motor,
    },
    {
      type: "ftc_elapsed_time_new",
      message0: "%1 = new ElapsedTime()",
      args0: [{ type: "field_input", name: "NAME", text: "timer" }],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.timing,
    },
    {
      type: "ftc_timer_reset",
      message0: "%1.reset()",
      args0: [{ type: "field_input", name: "NAME", text: "timer" }],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.timing,
    },
    {
      type: "ftc_while_timer_seconds",
      message0: "while %1.seconds() < %2 and opModeIsActive do %3",
      args0: [
        { type: "field_input", name: "TIMER", text: "timer" },
        { type: "field_number", name: "SECONDS", value: 2, min: 0.1, precision: 0.1 },
        { type: "input_statement", name: "BODY", check: "ftc_statement" },
      ],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.timing,
    },
    {
      type: "ftc_motors_stop_zero",
      message0: "stop motors %1",
      args0: [{ type: "field_input", name: "MOTORS", text: "leftMotor, rightMotor" }],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.motor,
    },
    {
      type: "ftc_sleep",
      message0: "sleep( %1 )",
      args0: [{ type: "field_number", name: "MS", value: 1000, min: 0 }],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.timing,
    },
    {
      type: "ftc_telemetry_ready",
      message0: "telemetry Status Ready + update",
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.telemetry,
    },
    {
      type: "ftc_telemetry_add",
      message0: "telemetry.addData( %1 , %2 )",
      args0: [
        { type: "field_input", name: "KEY", text: "Power" },
        { type: "field_input", name: "VAL", text: "power" },
      ],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.telemetry,
    },
    {
      type: "ftc_telemetry_update",
      message0: "telemetry.update()",
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.telemetry,
    },
    {
      type: "ftc_button_toggle",
      message0: "toggle %1 on gamepad1.a rising edge → %2",
      args0: [
        { type: "field_input", name: "FLAG", text: "intakeRunning" },
        { type: "field_input", name: "LAST", text: "lastA" },
      ],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.gamepad,
    },
    {
      type: "ftc_if_button",
      message0: "if gamepad1.%1 %2",
      args0: [
        {
          type: "field_dropdown",
          name: "BTN",
          options: [
            ["a", "a"],
            ["b", "b"],
            ["x", "x"],
            ["y", "y"],
            ["right_bumper", "right_bumper"],
            ["left_bumper", "left_bumper"],
          ],
        },
        { type: "input_statement", name: "BODY", check: "ftc_statement" },
      ],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.control,
    },
    {
      type: "ftc_declare_boost_if_bumper",
      message0: "double %1 = 1.0; if right_bumper %2 else %3",
      args0: [
        { type: "field_input", name: "VAR", text: "boostMultiplier" },
        { type: "field_number", name: "IF_VAL", value: 1 },
        { type: "field_number", name: "ELSE_VAL", value: 0.5, min: 0, max: 1, precision: 0.1 },
      ],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.control,
    },
    {
      type: "ftc_loop_count_increment",
      message0: "loopCount++",
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.control,
    },
    {
      type: "ftc_mecanum_teleop",
      message0: "mecanum drive teleop FL %1 FR %2 BL %3 BR %4",
      args0: [
        { type: "field_input", name: "FL", text: "frontLeft" },
        { type: "field_input", name: "FR", text: "frontRight" },
        { type: "field_input", name: "BL", text: "backLeft" },
        { type: "field_input", name: "BR", text: "backRight" },
      ],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.advanced,
    },
    {
      type: "ftc_pid_p_loop",
      message0: "P loop motor %1 target %2 Kp %3",
      args0: [
        { type: "field_input", name: "MOTOR", text: "turretMotor" },
        { type: "field_number", name: "TARGET", value: 500 },
        { type: "field_number", name: "KP", value: 0.01, min: 0.0001, precision: 0.0001 },
      ],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.advanced,
    },
    {
      type: "ftc_road_runner_trajectory",
      message0: "Road Runner follow trajectory (drive variable %1)",
      args0: [{ type: "field_input", name: "DRIVE", text: "drive" }],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.advanced,
    },
    {
      type: "ftc_pedro_follow_path",
      message0: "Pedro follow path (follower %1)",
      args0: [{ type: "field_input", name: "FOLLOWER", text: "follower" }],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.advanced,
    },
    {
      type: "ftc_limelight_poll",
      message0: "Limelight poll %1",
      args0: [{ type: "field_input", name: "LL", text: "limelight" }],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.advanced,
    },
    {
      type: "ftc_number",
      message0: "%1",
      args0: [{ type: "field_number", name: "NUM", value: 0.5 }],
      output: "Number",
      style: S.math,
    },
    {
      type: "ftc_comment",
      message0: "comment %1",
      args0: [{ type: "field_input", name: "TEXT", text: "TODO" }],
      previousStatement: "ftc_statement",
      nextStatement: "ftc_statement",
      style: S.structure,
    },
  ]);
}
