/** FTC primitive block types for toolbox filtering. */
export const FTC_BLOCK_TYPES = {
  linearOpMode: [
    "ftc_comment",
    "ftc_call_wait_for_start",
    "ftc_call_sleep",
    "ftc_call_idle",
    "ftc_call_telemetry_update",
    "ftc_call_telemetry_add_data",
    "ftc_reporter_op_mode_is_active",
    "ftc_reporter_is_active",
    "ftc_if_is_active",
    "ftc_elapsed_time_new",
    "ftc_elapsed_time_reset",
    "ftc_elapsed_time_seconds",
  ],
  gamepad: [
    "ftc_gamepad_stick_y",
    "ftc_gamepad_button",
    "ftc_gamepad_trigger",
  ],
  dcMotor: [
    "ftc_dc_motor_hw_get",
    "ftc_dc_motor_ex_hw_get",
    "ftc_dc_motor_set_power",
    "ftc_dc_motor_get_power",
    "ftc_dc_motor_set_mode",
    "ftc_dc_motor_set_target_position",
    "ftc_dc_motor_set_direction",
    "ftc_dc_motor_set_zero_power",
    "ftc_dc_motor_get_position",
    "ftc_dc_motor_is_busy",
    "ftc_dc_motor_ex_set_velocity",
    "ftc_while_is_busy",
  ],
  servo: [
    "ftc_servo_hw_get",
    "ftc_servo_set_position",
    "ftc_cr_servo_hw_get",
    "ftc_cr_servo_set_power",
  ],
  loops: ["controls_whileUntil", "controls_repeat_ext", "controls_if"],
  logic: ["logic_compare", "logic_operation", "logic_negate", "logic_boolean"],
  math: ["math_number", "math_arithmetic", "math_single"],
} as const;
